-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 21:51:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sisgeu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisgeu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisgeu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `sisgeu` ;

-- -----------------------------------------------------
-- Table `sisgeu`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`usuarios` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `curso` VARCHAR(150) NOT NULL,
  `instituicao` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_usuarios_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Estudantes universitários cadastrados no sistema';


-- -----------------------------------------------------
-- Table `sisgeu`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`categorias` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `idusuario` CHAR(36) NULL DEFAULT NULL COMMENT 'NULL = categoria padrão do sistema',
  `nome` VARCHAR(100) NOT NULL,
  `tipo` ENUM('despesa', 'receita', 'ambos') NOT NULL,
  `cor` CHAR(7) NOT NULL DEFAULT '#6366F1' COMMENT 'Hex color ex: #F97316',
  `icone` VARCHAR(50) NULL DEFAULT NULL,
  `padrao` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idx_categorias_usuario` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sisgeu`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Categorias de despesas e receitas';


-- -----------------------------------------------------
-- Table `sisgeu`.`orcamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`orcamentos` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `idusuario` CHAR(36) NOT NULL,
  `idcategoria` CHAR(36) NOT NULL,
  `mes` TINYINT NOT NULL,
  `ano` SMALLINT NOT NULL,
  `limite` DECIMAL(12,2) NOT NULL,
  `gasto_atual` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_orcamento_cat_mes_ano` (`idusuario` ASC, `idcategoria` ASC, `mes` ASC, `ano` ASC) VISIBLE,
  INDEX `idx_orcamentos_mes_ano` (`mes` ASC, `ano` ASC) VISIBLE,
  INDEX `fk_orcamentos_categoria` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_orcamentos_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `sisgeu`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orcamentos_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sisgeu`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Orçamentos mensais por categoria (RF05)';


-- -----------------------------------------------------
-- Table `sisgeu`.`alertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`alertas` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `idusuario` CHAR(36) NOT NULL,
  `idorcamento` CHAR(36) NULL DEFAULT NULL,
  `tipo` ENUM('orcamento_80', 'orcamento_100', 'meta_prazo', 'saldo_negativo') NOT NULL,
  `mensagem` TEXT NOT NULL,
  `lido` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idx_alertas_usuario_lido` (`idusuario` ASC, `lido` ASC) VISIBLE,
  INDEX `idx_alertas_orcamento` (`idorcamento` ASC) VISIBLE,
  CONSTRAINT `fk_alertas_orcamento`
    FOREIGN KEY (`idorcamento`)
    REFERENCES `sisgeu`.`orcamentos` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alertas_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sisgeu`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Notificações automáticas de orçamento (RF06)';


-- -----------------------------------------------------
-- Table `sisgeu`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`despesas` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `idusuario` CHAR(36) NOT NULL,
  `idcategoria` CHAR(36) NULL DEFAULT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('confirmado', 'pendente', 'cancelado') NOT NULL DEFAULT 'confirmado',
  `recorrente` TINYINT(1) NOT NULL DEFAULT '0',
  `periodicidade` ENUM('diario', 'semanal', 'mensal', 'anual') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_despesas_usuario` (`idusuario` ASC) VISIBLE,
  INDEX `idx_despesas_categoria` (`idcategoria` ASC) VISIBLE,
  INDEX `idx_despesas_data` (`data` ASC) VISIBLE,
  CONSTRAINT `fk_despesas_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `sisgeu`.`categorias` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_despesas_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sisgeu`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Registro de despesas dos estudantes (RF02)';


-- -----------------------------------------------------
-- Table `sisgeu`.`metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`metas` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `idusuario` CHAR(36) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `valor_alvo` DECIMAL(12,2) NOT NULL,
  `valor_atual` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `prazo` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_metas_usuario` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_metas_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sisgeu`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Metas financeiras dos estudantes (RF07)';


-- -----------------------------------------------------
-- Table `sisgeu`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgeu`.`receitas` (
  `id` CHAR(36) NOT NULL DEFAULT uuid(),
  `idusuario` CHAR(36) NOT NULL,
  `idcategoria` CHAR(36) NULL DEFAULT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `data` DATE NOT NULL,
  `fonte` VARCHAR(100) NOT NULL COMMENT 'Ex: bolsa, estágio, trabalho, mesada',
  `periodicidade` ENUM('unica', 'diario', 'semanal', 'mensal', 'anual') NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_receitas_usuario` (`idusuario` ASC) VISIBLE,
  INDEX `idx_receitas_categoria` (`idcategoria` ASC) VISIBLE,
  INDEX `idx_receitas_data` (`data` ASC) VISIBLE,
  CONSTRAINT `fk_receitas_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `sisgeu`.`categorias` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_receitas_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sisgeu`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Registro de receitas dos estudantes (RF03)';

USE `sisgeu`;

DELIMITER $$
USE `sisgeu`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `sisgeu`.`trg_alerta_orcamento_80`
AFTER INSERT ON `sisgeu`.`despesas`
FOR EACH ROW
BEGIN
    DECLARE v_orc_id      CHAR(36);
    DECLARE v_limite      DECIMAL(12,2);
    DECLARE v_gasto       DECIMAL(12,2);
    DECLARE v_nome_cat    VARCHAR(100);
    DECLARE v_percentual  DECIMAL(5,2);

    -- Busca orçamento ativo para a categoria/mês/ano
    SELECT o.id, o.limite, o.gasto_atual, c.nome
    INTO   v_orc_id, v_limite, v_gasto, v_nome_cat
    FROM   orcamentos o
    JOIN   categorias c ON c.id = o.categoria_id
    WHERE  o.usuario_id    = NEW.usuario_id
      AND  o.categoria_id  = NEW.categoria_id
      AND  o.mes           = MONTH(NEW.data)
      AND  o.ano           = YEAR(NEW.data)
    LIMIT 1;

    IF v_orc_id IS NOT NULL THEN
        -- Atualiza gasto_atual
        UPDATE orcamentos
        SET    gasto_atual = gasto_atual + NEW.valor
        WHERE  id = v_orc_id;

        SET v_percentual = ((v_gasto + NEW.valor) / v_limite) * 100;

        -- Alerta 80%
        IF v_percentual >= 80 AND v_percentual < 100 THEN
            INSERT INTO alertas (usuario_id, orcamento_id, tipo, mensagem)
            VALUES (
                NEW.usuario_id, v_orc_id, 'orcamento_80',
                CONCAT('Atenção! Você atingiu 80% do orçamento de "', v_nome_cat, '".')
            );
        END IF;

        -- Alerta 100%
        IF v_percentual >= 100 THEN
            INSERT INTO alertas (usuario_id, orcamento_id, tipo, mensagem)
            VALUES (
                NEW.usuario_id, v_orc_id, 'orcamento_100',
                CONCAT('Limite ultrapassado! O orçamento de "', v_nome_cat, '" foi excedido.')
            );
        END IF;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
