# Generated by Django 6.0.3 on 2026-03-26 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita'), ('ambos', 'Ambos')], max_length=10)),
                ('cor', models.CharField(default='#6366F1', max_length=7)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('padrao', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='confirmado', max_length=12)),
                ('recorrente', models.BooleanField(default=False)),
                ('periodicidade', models.CharField(blank=True, choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='idcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
                ('usuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'despesas',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name_plural': 'Metas',
                'db_table': 'metas',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('usuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'orcamentos',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('orcamento_80', 'Orçamento 80%'), ('orcamento_100', 'Orçamento 100%'), ('meta_prazo', 'Meta com Prazo'), ('saldo_negativo', 'Saldo Negativo')], max_length=20)),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('orcamento', models.ForeignKey(blank=True, db_column='idorcamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orcamento')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('fonte', models.CharField(max_length=100)),
                ('periodicidade', models.CharField(blank=True, choices=[('unica', 'Única'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='idcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
                ('usuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'db_table': 'receitas',
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['usuario'], name='categorias_idusuar_e276a2_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['usuario'], name='despesas_idusuar_ef003a_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['categoria'], name='despesas_idcateg_f5eb12_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['data'], name='despesas_data_8d9f28_idx'),
        ),
        migrations.AddIndex(
            model_name='meta',
            index=models.Index(fields=['usuario'], name='metas_idusuar_ebabe0_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['mes', 'ano'], name='orcamentos_mes_c19924_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['categoria'], name='orcamentos_idcateg_272b9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('usuario', 'categoria', 'mes', 'ano')},
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['usuario', 'lido'], name='alertas_idusuar_1c390b_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['orcamento'], name='alertas_idorcam_853ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['usuario'], name='receitas_idusuar_26045b_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['categoria'], name='receitas_idcateg_e608c6_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['data'], name='receitas_data_a75a8c_idx'),
        ),
    ]
